AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/helpers/*'
    - 'app/mailers/*'
    - 'app/models/*'
    - 'app/controllers/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
